auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("categories", views.categories_list, name="categories"),
    path("categories/<str:category_name>", views.category, name="category"),
    path("listings/create_listing", views.create_listing, name="create"),
    path("listings/<int:listing_id>", views.listing, name="listing"),
    path("listings/<int:listing_id>/bid", views.bid_listing, name="bid_listing"),
    path("listings/<int:listing_id>/close", views.close_listing, name="close_listing"),
    path("listings/<int:listing_id>/comment", views.comment_listing, name="comment"),
    path("listings/<int:listing_id>/watch", views.watch_listing, name="watch_listing"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("watchlist", views.watchlist, name="watchlist"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator
from datetime import datetime, timedelta


class User(AbstractUser):
    def __str__(self):
        return f"{self.username}"


class Category(models.Model):
    name = models.CharField(max_length=32)

    class Meta:
        # order alphabetically
        ordering = ("name",)

    @property
    def count_active_listings(self):
        return Listing.objects.filter(
            category=Category.objects.get(name=self.name),
            ended_manually=False,
            end_time__gte=datetime.now(),
        ).count()

    def __str__(self) -> str:
        return str(self.name)


class Listing(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField(max_length=512)
    starting_bid = models.DecimalField(
        decimal_places=2, max_digits=12, validators=[MinValueValidator(0.01)]
    )
    img = models.CharField(blank=True, null=True, max_length=256)
    category = models.ForeignKey(
        Category,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name="listings",
    )

    creator: User = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="listings"
    )
    watchers = models.ManyToManyField(User, blank=True, related_name="watchlist")

    DURATIONS = (
        (1, "One Day"),
        (3, "Three Days"),
        (7, "One Week"),
        (14, "Two Weeks"),
        (28, "Four Weeks"),
    )
    duration = models.IntegerField(choices=DURATIONS, default=7)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    ended_manually = models.BooleanField(default=False)

    def __str__(self):
        return f"Listing #{self.id}: {self.creator.username} | {self.title}"

    def save(self, *args, **kwargs):
        self.start_time = datetime.now()
        self.end_time = self.start_time + timedelta(days=self.duration)
        super().save(*args, **kwargs)  # call existing save() method

    def ended(self):
        if self.ended_manually or self.end_time < timezone.now():
            return True
        else:
            return False


class Bid(models.Model):
    bid = models.DecimalField(
        decimal_places=2, max_digits=12, validators=[MinValueValidator(0.01)]
    )
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bids")
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="bids")

    class Meta:
        ordering = ("-bid",)

    def __str__(self) -> str:
        return f"Bid #{self.id}: {self.bidder} on {self.listing} for {self.bid}"


class Comment(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=1024)
    listing = models.ForeignKey(
        Listing,
        blank=True,
        null=True,
        on_delete=models.CASCADE,
        related_name="comments",
    )

    class Meta:
        ordering = ("-comment",)

    def __str__(self) -> str:
        return f"Comment #{self.id}: {self.creator} on {self.listing}"

auctions/forms.py
from django import forms
from .models import Category, Listing


class NewListingForm(forms.Form):

    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "autofocus": True,
                "placeholder": "Title:",
            }
        )
    )
    description = forms.CharField(
        widget=forms.Textarea(
            attrs={"class": "form-control", "placeholder": "Description:"}
        )
    )
    starting_bid = forms.IntegerField(
        widget=forms.NumberInput(attrs={"class": "form-control", "placeholder": "25"})
    )
    duration = forms.ChoiceField(
        required=False,
        choices=Listing.DURATIONS,
        widget=forms.Select(attrs={"class": "form-control", "value": "7"}),
    )
    img = forms.URLField(
        required=False,
        widget=forms.URLInput(
            attrs={"class": "form-control", "placeholder": "www.example.com/joe.png"}
        ),
    )
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        widget=forms.Select(attrs={"class": "form-control"}),
    )


class BidForm(forms.Form):
    bid = forms.IntegerField(widget=forms.NumberInput(attrs={"class": "form-control"}))


class CommentForm(forms.Form):
    comment = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "class": "form-control",
                "rows": "1",
                "placeholder": "Comment:",
                "type": "submit",
            }
        )
    )

auctions/views.py
from datetime import datetime
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import User, Listing, Comment, Category, Bid
from .forms import BidForm, CommentForm, NewListingForm


def index(request):
    active_listings = Listing.objects.filter(
        ended_manually=False, end_time__gte=datetime.now()
    )
    return render(request, "auctions/index.html", {"listings": active_listings})


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(
                request,
                "auctions/login.html",
                {"message": "Invalid username and/or password."},
            )
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(
                request, "auctions/register.html", {"message": "Passwords must match."}
            )

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(
                request,
                "auctions/register.html",
                {"message": "Username already taken."},
            )
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")


def listing(request, listing_id: int, message: str = None):
    listing = Listing.objects.get(pk=listing_id)
    return render(
        request,
        "auctions/listing.html",
        {
            "listing": listing,
            "message": message,
            "bid_form": BidForm(),
            "comment_form": CommentForm(),
        },
    )


@login_required(login_url="auctions/login.html")
def bid_listing(request, listing_id: int):
    listing = Listing.objects.get(pk=listing_id)
    if request.method == "POST":
        form = BidForm(request.POST)
        if form.is_valid():
            user_bid = form.cleaned_data["bid"]
            if listing.bids.all():
                highest_bid = max([bid.bid for bid in listing.bids.all()])
            else:
                highest_bid = listing.starting_bid
            if user_bid > highest_bid:
                Bid(bid=user_bid, bidder=request.user, listing=listing).save()
                return HttpResponseRedirect(
                    reverse("listing", kwargs={"listing_id": listing_id})
                )
            else:
                return HttpResponseRedirect(
                    reverse(
                        "listing",
                        kwargs={
                            "listing_id": listing_id,
                            "message": "Your bid wasn't big enough!",
                        },
                    )
                )


@login_required(login_url="auctions/login.html")
def comment_listing(request, listing_id: int):
    listing = Listing.objects.get(pk=listing_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.cleaned_data["comment"]
            Comment(listing=listing, creator=request.user, comment=comment).save()
            return HttpResponseRedirect(
                reverse("listing", kwargs={"listing_id": listing_id})
            )
    return HttpResponseRedirect(reverse("listing", kwargs={"listing_id": listing_id}))


@login_required(login_url="auctions/login.html")
def create_listing(request):
    if request.method == "POST":
        form = NewListingForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            start_bid = form.cleaned_data["starting_bid"]
            try:
                img = form.cleaned_data["img"]
            except:
                img = None
            try:
                category = Category.objects.filter(name=form.cleaned_data["category"])
                category.save()
            except:
                category = None
            duration = int(form.cleaned_data["duration"]) or None
            listing = Listing(
                title=title,
                description=description,
                starting_bid=start_bid,
                img=img,
                category=category,
                duration=duration,
                creator=request.user,
            )
            listing.save()
            return HttpResponseRedirect(reverse("index"))
    return render(request, "auctions/create.html", {"form": NewListingForm()})


def close_listing(request, listing_id: int):
    listing = Listing.objects.get(pk=listing_id)
    if request.user == listing.creator:
        listing.ended_manually = True
        listing.save()

    return HttpResponseRedirect(reverse("listing", kwargs={"listing_id": listing_id}))


def watch_listing(request, listing_id: int):
    listing = Listing.objects.get(pk=listing_id)
    watchlist = request.user.watchlist
    if listing in watchlist.all():
        watchlist.remove(listing)
    else:
        watchlist.add(listing)
    return HttpResponseRedirect(reverse("listing", kwargs={"listing_id": listing_id}))


def category(request, category_name: str):
    cat = Category.objects.get(name=category_name)
    auctions = Listing.objects.filter(
        category=cat, ended_manually=False, end_time__gte=datetime.now()
    )
    return render(
        request,
        "auctions/index.html",
        {"listings": auctions, "category_name": category_name},
    )


def categories_list(request):
    categories = Category.objects.all()
    return render(request, "auctions/categories.html", {"categories": categories})


def watchlist(request):
    listings = request.user.watchlist.all()
    return render(request, "auctions/index.html", {"listings": listings})

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block title %}Categories{% endblock title %}

{% block body %} 
    <h2 class="text-center text-light">Categories</h2>
    <div class="container">
        <div class="row justify-content-center text-light">
            <div class="col-md-6 listing-card text-center">
                {% for category in categories %}
                    <a class="nav-link" href="{% url 'category' category.name %}">
                        <h3>{{ category.name }}: <p class="badge badge-pill badge-info">{{ category.count_active_listings }}</p></h3>
                    </a>
                    <br>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock body %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %} 

{% block body %}

    <h2 class="text-center text-light">Create a listing</h2>
    <div class="container text-light text-center">
        <div class="row justify-content-center">
            <div class="col-sm-6 listing-card">
                <form action="{% url 'create' %}" method="post">
                    {% csrf_token %} 
                    <div class="form-group">
                        {{ form.title }}
                    </div>
                    <div class="form-group">
                        {{ form.description }}
                    </div>
                    <label for="id_starting_bid">Starting Bid:</label>
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text">€</span>
                        </div>
                        {{ form.starting_bid }}
                        <div class="input-group-append">
                            <span class="input-group-text">.00</span>
                        </div> 
                    </div>
                    <label for="id_duratioon">Optional: Duration</label>
                    <div class="input-group mb-3">
                        {{ form.duration }}
                    </div>
                    <label for="id_img_url">Optional: Image URL</label>
                    <div class="input-group mb-3">
                        {{ form.img }}
                    </div>
                    <label for="id_category">Optional: Category</label>
                    <div class="input-group mb-3">
                        {{ form.category }}
                    </div>
                    <input class="btn mbutton mteal" type="submit" value="Create">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load static %}

{% block title %}
    {% if category_name %} 
        {{ category_name }}
    {% else %}
        Auctions
    {% endif %}
{% endblock title %}

{% block body %}
    <h2 class="text-center text-light">
        {% if category_name %} 
            {{ category_name }}
        {% else %}
            Active Listings
        {% endif %}
    </h2>
    <div class="container">
        <div class="row align-items-md-stretch justify-content-center">
            {% for listing in listings %}
                <div class="col-lg-6">
                    {% if listing.img %}
                        <div class="container text-center product-card">
                            <img src="{{ listing.img }}" class="thumbnail">
                        </div>
                    {% endif %}
                    <div class="box-element product">
                        <h6><strong>{{ listing.title }}</strong></h6>
                        <hr>
                        {% if user.is_authenticated %}
                            {% if listing in user.watchlist.all %}
                                <a class="btn mbutton myellow" href="{% url 'watch_listing' listing.id %}">Remove from Watchlist</a>
                            {% else %}
                                <a class="btn mbutton myellow" href="{% url 'watch_listing' listing.id %}">Add to Watchlist</a>
                            {% endif %}
                        {% endif %}
                        <a class="btn mbutton mteal" href="{% url 'listing' listing.id %}" style="padding: 0.375rem 1.25rem;">View</a>
                        <h4 style="float: right;">€
                            {% if listing.bids.count > 0 %}
                                {{ listing.bids.first.bid }}
                            {% else %}
                                {{ listing.starting_bid }}
                            {% endif %}
                        </h4>
                    </div>
                </div>
            {% empty %}
            <div class="container text-center text-light">
                <img class="img img-fluid rounded" style="height: 500px;" src="{% static 'auctions/404.png' %}">
                <h2>
                    {% if category_name %} 
                        There are no active listings in {{ category_name }} at the moment.
                    {% else %}
                        There are no active listings at the moment.
                    {% endif %}
                </h2>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}Auctions{% endblock title %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/f.css' %}" rel="stylesheet" type="text/css">
    </head>
    <body>
        <h1 class="text-center text-light">Auctions</h1>
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom text-center text-light">
            <div class="text-start text-light col-md-3">
                {% if user.is_authenticated %}
                    Signed in as <strong>{{ user.username }}</strong>.
                {% else %}
                    Not signed in.
                {% endif %}
            </div>
            <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'index' %}" class="nav-link px-2">Active Listings</a></li>
                {% if user.is_authenticated %}
                    <li><a class="nav-link px-2 link-dark" href="{% url 'create' %}">Create Listing</a></li>
                {% endif %}
                <li><a href="{% url 'categories' %}" class="nav-link px-2">Categories</a></li>
                {% if user.is_authenticated %}
                    <li><a class="nav-link px-2 link-dark" href="{% url 'watchlist' %}">Watchlist <p class="badge badge-pill badge-info">{{ user.watchlist.count }}</p></a></li>
                {% endif %}
            </ul>
            <div class="col-md-3 text-end">
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}"><button class="btn mbutton myellow">Log Out</button></a>
            {% else %}
                <a href="{% url 'login' %}"><button type="button" class="btn mbutton mteal">Login</button></a>
                <a href="{% url 'register' %}"><button type="button" class="btn mbutton mteal mreverse">Sign-up</button></a>
            {% endif %}
            </div>
        </header>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends 'auctions/layout.html' %}

{% block title %}
    Viewing: {{ listing.title }}
{% endblock  %}

{% block body %}
    <div class="container text-center">
        <div class="row justify-content-center text-light">
            <div class="col-lg-6 listing-card">
                <h3><strong>{{ listing.title }}</strong></h3>
                {% if listing.img %}
                    <img src="{{ listing.img }}" class="img img-fluid" rounded>
                {% endif %}
                <p class="lead light-themed">{{ listing.description }}</p>
                {% if not listing.ended %}
                    <p class="lead">
                        <strong class="light-themed">
                            {% if listing.bids.count > 0 %}
                                Current bid:</strong> €{{ listing.bids.first.bid }}
                            {% else %}
                                Price:</strong> €{{ listing.starting_bid }}
                            {% endif %}
                    </p>
                    {% if listing.bids.count > 0 %}
                        <p class="badge badge-pill badge-info">Bids: {{ listing.bids.count }}</p>
                    {% endif %}
                    {% if message %} 
                        <p class="badge badge-pill badge-danger">{{ message }}</p>
                    {% endif %}
                    {% if listing.bids.first.bidder == user %}
                        <p class="badge badge-pill badge-success">You're in the lead!</p>
                    {% endif %}
                    {% if listing.creator == user %}
                        <p><a class="btn mbutton mred" href="{% url 'close_listing' listing.id %}">End the listing</a></p>
                    {% elif user.is_authenticated %}
                        <form action="{% url 'bid_listing' listing.id %}" method="post">
                            {% csrf_token %}
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text">€</span>
                                </div>
                                    {{ bid_form.bid }}
                                <div class="input-group-append">
                                    <span class="input-group-text">.00</span>
                                </div> 
                            </div>
                            <input class="btn mbutton mblue" type="submit" value="Place Bid">
                        </form>
                        {% if listing in user.watchlist.all %}
                            <p><a class="btn mbutton myellow" href="{% url 'watch_listing' listing.id %}">Remove from Watchlist</a></p>
                        {% else %}
                            <p><a class="btn mbutton myellow" href="{% url 'watch_listing' listing.id %}">Add to Watchlist</a></p>
                        {% endif %}
                    {% else %}
                        <p><a href="{% url 'login' %}" class="bid_login">Please login to place a bid.</a></p>
                    {% endif %}
                {% else %}
                    <p class="lead">
                        <strong class="light-themed">
                            {% if listing.bids.count > 0 %}
                                Final Bid:</strong> €{{ listing.bids.first.bid }}
                            {% else %}
                                Final Price:</strong> €{{ listing.starting_bid }}
                            {% endif %}
                    </p>
                    {% if listing.bids.first.bidder == user %}
                        <p class="badge badge-pill badge-success">You won!</p>
                    {% endif %}
                {% endif %}
                <p class="lead">
                    {% if listing.category %}
                        <strong>Category</strong>: <a href="{% url 'category' listing.category.name %}">{{ listing.category.name }}</a>
                    {% else %}
                        No category listed.
                    {% endif %}
                </p>
                <p><strong>Listing created</strong>: {{ listing.start_time }}</p>
                <p><strong>Listing ends</strong>: {{  listing.end_time }}</p>
            </div>
        </div>
        <div class="container text-center text-light">
            <div class="row justify-content-center comment-section">
                <div class="col-lg-4">
                    <span><h3 class="border-bottom">Comments:</h3></span>
                    {% if user.is_authenticated and not listing.ended %}
                        <form method="post" action="{% url 'comment' listing.id %}">
                            {% csrf_token %}
                            <div class="input-group">
                                {{ comment_form.comment }}
                                <input type="submit" class="btn mbutton mblue" value="Submit">
                            </div>
                        </form>
                    {% elif user.is_authenticated and listing.ended %}
                        <p>This auction has ended.</p>
                    {% else %} 
                        <p><a href="{% url 'login' %}" class="bid_login" style="border-radius: 5px;">Please login to place a comment.</a></p>
                    {% endif %}
                </div>
                <div class="col-lg-8 text-center justify-content-center">
                    <div class="row text-center">
                        {% for comment in listing.comments.all %}
                            <div class="col-lg-2"></div>
                            <div class="col-lg-8">
                                <div class="box-element product">
                                    <h6><strong>{{ comment.creator }}</strong></h6>                                
                                    <h4>{{ comment.comment }}</h4>
                                </div>
                            </div>
                            <div class="col-lg-2"></div>
                        {% empty %}
                            <div class="col-lg-2"></div>
                            <div class="col-lg-8">
                                <h4 class="py-4">No comments have been made.</h4>
                            </div>
                            <div class="col-lg-2"></div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2 class="text-center text-light">Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <div class="container text-center text-light">
        <div class="row justify-content-center">
            <div class="col-sm-4 listing-card">
                <form action="{% url 'login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input autofocus class="form-control" type="text" name="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="password" name="password" placeholder="Password">
                    </div>
                    <input class="btn mbutton mblue" type="submit" value="Login">
                </form>
            </div>
        </div>
        Don't have an account? <a href="{% url 'register' %}">Register here.</a>
    </div>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2 class="text-center text-light">Register</h2>
    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <div class="container text-light text-center">
        <div class="row justify-content-center">
            <div class="col-sm-4 listing-card">
                <form action="{% url 'register' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input class="form-control" autofocus type="text" name="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="email" name="email" placeholder="Email Address">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="password" name="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
                    </div>
                    <input class="btn mbutton mblue" type="submit" value="Register">
                </form>
            </div>
        </div>
        Already have an account? <a href="{% url 'login' %}">Log In here.</a>
    </div>

{% endblock %}